FROM httpd:2.4

### Apache (httpd) Docker image
# docker build -t httpd-docker-sample:1.0 .
# docker images
# docker run -d --name httpd-docker-01 -p 80:80 httpd-docker-sample:1.0
# docker ps
# http://localhost